///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2006 Impulse Accelerated Technologies, Inc.
// 

#define STREAMDEPTH 1024	/* buffer size for FIFO in hardware */
#define STREAMWIDTH 32	/* buffer width for FIFO in hardware */
#define INPUT_FILE "filter_in.dat"
#define OUTPUT_FILE "filter_out.dat"


