///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.
// 
// BasicStream_hw.c: includes the hardware process and configuration
// function.
//
// See additional comments in BasicStream.h.
//

#include "co.h"
#include "cosim_log.h"
#include "BasicStream.h"

// Software process declarations (see BasicStream_sw.c)
extern void Producer(co_stream HWinput);
extern void Consumer(co_stream HWoutput);

//
// This is the hardware process.
// 
void HWproc(co_stream HWinput, co_stream HWoutput)
{
	co_int1 nSample;
	IF_SIM(int samplesread; int sampleswritten;)
	
	IF_SIM(cosim_logwindow log;)
	IF_SIM(log = cosim_logwindow_create("HWproc");)
	
	do {	// Hardware processes run forever
		IF_SIM(samplesread=0; sampleswritten=0;)
	
		co_stream_open(HWinput, O_RDONLY, INT_TYPE(STREAMWIDTH));
		co_stream_open(HWoutput, O_WRONLY, INT_TYPE(STREAMWIDTH));
	
		// Read values from the stream
		while ( co_stream_read(HWinput, &nSample, sizeof(co_int1)) == co_err_none ) {
			IF_SIM(samplesread++;)
	
			// Sample is now in variable nSample.
			// Add your processing code here.
	
			nSample = ~nSample;
			co_stream_write(HWoutput, &nSample, sizeof(co_int1));
			IF_SIM(sampleswritten++;)
		}
		co_stream_close(HWinput);
		co_stream_close(HWoutput);
		IF_SIM(cosim_logwindow_fwrite(log,
			"Closing filter process, samples read: %d, samples written: %d\n",
			samplesread, sampleswritten);)
	
		IF_SIM(break;)	// Only run once for desktop simulation
	} while(1);
}

//
// Impulse C configuration function
//
void config_BasicStream(void *arg)
{
	co_stream HWinput;
	co_stream HWoutput;
	
	co_process HWproc_process;
	co_process producer_process;
	co_process consumer_process;

	IF_SIM(cosim_logwindow_init();)
	
	HWinput = co_stream_create("HWinput", INT_TYPE(STREAMWIDTH), STREAMDEPTH);
	HWoutput = co_stream_create("HWoutput", INT_TYPE(STREAMWIDTH), STREAMDEPTH);
	
	producer_process = co_process_create("Producer", (co_function)Producer,
										 1,
										 HWinput);
	
	HWproc_process = co_process_create("HWproc", (co_function)HWproc,
									2,
									HWinput,
									HWoutput);
	
	consumer_process = co_process_create("Consumer",(co_function)Consumer,
										 1,
										 HWoutput);
	
	co_process_config(HWproc_process, co_loc, "pe0");  
}

co_architecture co_initialize(int param)
{
	return(co_architecture_create("BasicStream_arch","Generic",config_BasicStream,(void *)param));
}

