///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.
// 
// BasicStream_sw.c: includes the software test bench processes and
// main() function.
//

#include <stdio.h>
#include "co.h"
#include "cosim_log.h"
#include "BasicStream.h"

extern co_architecture co_initialize(void *);

void Producer(co_stream HWinput)
{
	int i;
	co_int1 value;
	IF_SIM(cosim_logwindow log = cosim_logwindow_create("Producer");)

	// Send some values to the hardware input stream.
	co_stream_open(HWinput, O_WRONLY, INT_TYPE(STREAMWIDTH));
	for (i = 0; i < 2; i++) 
	{
		value = 0;
		IF_SIM(cosim_logwindow_fwrite(log, "  -> 0x%x produced\n", value);)
		printf("  -> 0x%x produced\n", value);
		co_stream_write(HWinput, &value, sizeof(co_int1));
	}
	co_stream_close(HWinput);
}

void Consumer(co_stream HWoutput)
{
	co_int1 testValue;
	unsigned int count = 0;

	IF_SIM(cosim_logwindow log = cosim_logwindow_create("Consumer");)

	co_stream_open(HWoutput, O_RDONLY, INT_TYPE(STREAMWIDTH));
  
	while ( co_stream_read(HWoutput, &testValue, sizeof(co_int1)) == co_err_none ) {
		IF_SIM(cosim_logwindow_fwrite(log, "  -> 0x%x consumed\n", testValue);)
		printf("  -> 0x%x consumed\n", testValue);
		count++;
	}
	co_stream_close(HWoutput);
}

int main(int argc, char *argv[])
{
	co_architecture my_arch;
	void *param = NULL;
	int c;

	printf("Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.\n");
	printf("--------------------------------------------------------------------------\n");
	printf("Basic Stream: Producer -----> HW process -----> Consumer\n\n");
  
	my_arch = co_initialize(param);
	co_execute(my_arch);

	printf("\n\nApplication complete. Press the Enter key to continue.\n");
	c = getc(stdin);

	return(0);
}


