
# ------------------------------------------------------------------
#
# CAUTION: This file is automatically generated by libgen.
# Version: Xilinx EDK 12.3 EDK_MS3.70d
# DO NOT EDIT.
#
# Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

# 
# Description: Configuration parameters for Standalone Makefile
#
# ------------------------------------------------------------------

LIBS = standalone_libs
