///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2006 Impulse Accelerated Technologies, Inc.
// 

#define STREAMDEPTH 2	/* buffer size for FIFO in hardware */
#define STREAMWIDTH 1	/* buffer width for FIFO in hardware */

// Added function prototypes
void Producer(co_stream HWinput);
void Consumer(co_stream HWoutput);

// Added interface declarations
co_stream HWinput;
co_stream HWoutput;
