///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.
// 
// BasicStream_sw.c: includes the software test bench processes and
// main() function.
//

#include <stdio.h>
#include "co.h"
#include "cosim_log.h"
#include "BasicStream.h"

extern co_architecture co_initialize(void *);

void Producer(co_stream HWinput)
{
	int i;
	co_int1 value;
	IF_SIM(cosim_logwindow log = cosim_logwindow_create("Producer");)

	// Send some values to the hardware input stream.
	co_stream_open(HWinput, O_WRONLY, INT_TYPE(STREAMWIDTH));
	for (i = 0; i < 2; i++) 
	{
		value = 0;
		co_stream_write(HWinput, &value, sizeof(co_int1));
	}
	xil_printf("producer done! %d\n", i);
	co_stream_close(HWinput);
}

void Consumer(co_stream HWoutput)
{
	co_int1 testValue;
	unsigned int count = 0;
	
	co_stream_open(HWoutput, O_RDONLY, INT_TYPE(STREAMWIDTH));
  
    // Read some values from the stream
	while ( co_stream_read(HWoutput, &testValue, sizeof(co_int1)) == co_err_none ) {
		count++;
	}
	xil_printf("consumer done! %d\n", count);
	co_stream_close(HWoutput);
}



