/*******************************************************************************
 DO NOT EDIT
 This file was automatically generated by the Impulse C Compiler.

 Copyright (c) 2002-2011 by Impulse Accelerated Technologies, Inc.
 All rights reserved.

 This source file may be used and redistributed without charge
 subject to the provisions of the IMPULSE ACCELERATED TECHNOLOGIES,
 INC. REDISTRIBUTABLE IP LICENSE AGREEMENT, and provided that this
 copyright statement is not removed from the file, and that any
 derivative work contains this copyright notice.

 Stage Master is Copyright 2002-2005, Green Mountain Computing Systems, Inc.
 All rights reserved.
********************************************************************************/

#include "co.h"

/* Architecture Includes */
#include <stdlib.h>
#include "xio.h"
#include "xparameters.h"


extern void *alloc_shared(size_t);

/* Run Procedures */
extern void Producer(co_signal, co_stream);
extern void AESproc(co_signal, co_stream, co_stream);
extern void Consumer(co_stream);

co_architecture co_initialize(void *arg)

{
  co_stream AESdataStream;
  co_stream AESoutputStream;
  co_signal AESinputSignal;

  AESdataStream=co_stream_create("AESdataStream",INT_TYPE(8),177);
  AESoutputStream=co_stream_create("AESoutputStream",INT_TYPE(8),177);
  AESinputSignal=co_signal_create("AESinputSignal");
  co_process_create("Producer",(co_function)Producer,
                    2,
                    AESinputSignal,
                    AESdataStream);
  co_process_create("Consumer",(co_function)Consumer,
                    1,
                    AESoutputStream);

  /* Architecture Initialization */
  co_stream_attach(AESdataStream,XPAR_PLB_AES_ARCH_0_BASEADDR+0,HW_INPUT);
  co_stream_attach(AESoutputStream,XPAR_PLB_AES_ARCH_0_BASEADDR+16,HW_OUTPUT);
  co_signal_attach(AESinputSignal,XPAR_PLB_AES_ARCH_0_BASEADDR+32,HW_INPUT);

  return(NULL);

}
