///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2006 Impulse Accelerated Technologies, Inc.
// 

#define STREAMDEPTH 2	/* buffer size for FIFO in hardware */
#define STREAMWIDTH 1	/* buffer width for FIFO in hardware */


