------------------------------------------------------------------------
-- DO NOT EDIT
-- This file was automatically generated by the Impulse C Compiler.
-- 
-- Impulse C is Copyright 2002-2011, Impulse Accelerated Technologies, Inc.
-- 
-- Stage Master is Copyright 2002-2011, Green Mountain Computing Systems, Inc.
-- 
-- All rights reserved.
------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

library impulse;
use impulse.components.all;

library impulse;
use impulse.mem_if_components.all;

entity BubbleSort_arch is
  port (
    reset : in std_ulogic;
    sclk : in std_ulogic;
    clk : in std_ulogic;
    p_Producer_input_en : in std_ulogic;
    p_Producer_input_eos : in std_ulogic;
    p_Producer_input_data : in std_ulogic_vector (31 downto 0);
    p_Producer_input_rdy : out std_ulogic;
    p_Consumer_output_en : in std_ulogic;
    p_Consumer_output_data : out std_ulogic_vector (31 downto 0);
    p_Consumer_output_eos : out std_ulogic;
    p_Consumer_output_rdy : out std_ulogic);
end;

architecture structure of BubbleSort_arch is
  component Sorter is
    port (
    reset : in std_ulogic;
    sclk : in std_ulogic;
    clk : in std_ulogic;
    p_input_rdy : in std_ulogic;
    p_input_en : inout std_ulogic;
    p_input_eos : in std_ulogic;
    p_input_data : in std_ulogic_vector (31 downto 0);
    p_output_rdy : in std_ulogic;
    p_output_en : inout std_ulogic;
    p_output_eos : out std_ulogic;
    p_output_data : out std_ulogic_vector (31 downto 0)
    );
  end component;

  signal p_Sorter_input_rdy : std_ulogic;
  signal p_Sorter_input_en : std_ulogic;
  signal p_Sorter_input_eos : std_ulogic;
  signal p_Sorter_input_data : std_ulogic_vector (31 downto 0);
  signal p_Sorter_output_rdy : std_ulogic;
  signal p_Sorter_output_en : std_ulogic;
  signal p_Sorter_output_eos : std_ulogic;
  signal p_Sorter_output_data : std_ulogic_vector (31 downto 0);
  signal local_reset : std_ulogic;
begin
  local_reset <= reset;

  Sorter0: Sorter
    port map (
      reset => local_reset,
      sclk => sclk,
      clk => clk,
      p_input_rdy => p_Sorter_input_rdy,
      p_input_en => p_Sorter_input_en,
      p_input_eos => p_Sorter_input_eos,
      p_input_data => p_Sorter_input_data,
      p_output_rdy => p_Sorter_output_rdy,
      p_output_en => p_Sorter_output_en,
      p_output_eos => p_Sorter_output_eos,
      p_output_data => p_Sorter_output_data
    );

  inst0: stream
    generic map (
      datawidth => 32,
      addrwidth => 5
    )
    port map (
      reset => local_reset,
      clk => clk,
      input_en => p_Producer_input_en,
      input_rdy => p_Producer_input_rdy,
      input_eos => p_Producer_input_eos,
      input_data => p_Producer_input_data,
      output_en => p_Sorter_input_en,
      output_rdy => p_Sorter_input_rdy,
      output_eos => p_Sorter_input_eos,
      output_data => p_Sorter_input_data
    );

  inst1: stream
    generic map (
      datawidth => 32,
      addrwidth => 5
    )
    port map (
      reset => local_reset,
      clk => clk,
      input_en => p_Sorter_output_en,
      input_rdy => p_Sorter_output_rdy,
      input_eos => p_Sorter_output_eos,
      input_data => p_Sorter_output_data,
      output_en => p_Consumer_output_en,
      output_rdy => p_Consumer_output_rdy,
      output_eos => p_Consumer_output_eos,
      output_data => p_Consumer_output_data
    );

end;
